name: Resolve tag files

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAGES_DEPLOYMENT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name Github Actions
          git config --global user.email actions@github.com

      - name: Get short repository name
        run: echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*\/} >> $GITHUB_ENV

      - name: Update push tagfile
        run: |
          wget "${{ inputs.url }}/$REPOSITORY_NAME/$REPOSITORY_NAME.tag"
          git add -f "$REPOSITORY_NAME.tag"
          git commit -m "[skip ci] Update tagfile in main"
          git push
